# Generated by Django 5.2.7 on 2025-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('social_worker', models.TextField()),
                ('mental_illness', models.TextField()),
                ('condition_severity', models.TextField()),
                ('additonal_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Age', models.IntegerField()),
                ('condition', models.TextField()),
                ('drug', models.TextField()),
                ('vital_pulse', models.CharField()),
                ('vital_temp', models.CharField()),
                ('vital_pain', models.CharField()),
                ('vital_bp', models.CharField()),
                ('vital_resp', models.CharField()),
                ('input_in', models.CharField()),
                ('input_out', models.CharField()),
                ('water_balance', models.CharField()),
                ('doc_notes', models.CharField()),
                ('status', models.CharField()),
                ('bill', models.CharField()),
                ('lab', models.CharField()),
                ('med_history', models.TextField()),
                ('appointment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.IntegerField()),
                ('occupation', models.TextField()),
                ('unique_id', models.CharField()),
            ],
        ),
    ]
