# Generated by Django 5.2.7 on 2025-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_hospital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
