# Generated by Django 5.2.7 on 2025-12-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_rename_additonal_notes_mind_additonalnotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mind',
            old_name='additonalnotes',
            new_name='additonalnote',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_date',
            new_name='appointmentdate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_purpose',
            new_name='appointmentpurpose',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_staff',
            new_name='appointmentstaff',
        ),
    ]
