# Generated by Django 5.2.7 on 2025-12-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_rename_additonalnotes_mind_additonalnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mind',
            old_name='additonalnote',
            new_name='additionalnote',
        ),
    ]
