# Generated by Django 5.2.7 on 2025-12-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_rename_additonalnote_mind_additionalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new.hospital'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new.hospital'),
        ),
    ]
